src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operation settings of your loyalty program.</description>
    <fields>
        <fullName>GRSPointType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GRS Point Type</label>
        <referenceTo>FieloPLT__PointType__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>GRSPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__ProviderOrder__c.object
<CustomObject>
    <description>Order number of the individual or entity which provides Rewards (e.g. Amazon).</description>
    <fields>
        <fullName>FieloPLT__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It shows the related Provider of the Provider Order. Provider always is a SFDC Account, either a Person or Business Account.</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider Orders</relationshipLabel>
        <relationshipName>ProviderOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>It allows you to choose the Provider Order status. There are two available statuses: Open, when the Order is created and Delivered, when Provider has already fullfiled delivery.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GRSOrderNumber__c</fullName>
        <externalId>true</externalId>
        <label>GRS Order Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Provider Order</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Provider Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__RedemptionItem__c.object
<CustomObject>
    <description>Items which are part of a Redemption order.</description>
    <fields>
        <fullName>FieloPLT__Points__c</fullName>
        <description>Points needed to redeem the Redemption item</description>
        <inlineHelpText>Points needed to redeem the Redemption item.</inlineHelpText>
        <label>Points</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FieloPLT__ProviderOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It shows the Provider Order related to the Redemption.</description>
        <inlineHelpText>It shows the Provider Order related to the Redemption.</inlineHelpText>
        <label>Provider Order</label>
        <referenceTo>FieloPLT__ProviderOrder__c</referenceTo>
        <relationshipLabel>Redemption Items</relationshipLabel>
        <relationshipName>RedemptionItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Number of Redemption items.</description>
        <inlineHelpText>Number of Redemption items.</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>Redemption item status.</description>
        <inlineHelpText>Redemption item status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reverted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GRSOrderId__c</fullName>
        <externalId>true</externalId>
        <label>GRS Order Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Redemption Item</label>
    <nameField>
        <displayFormat>RI-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemption Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RESTOrderUpdateTest.cls
@isTest
public class RESTOrderUpdateTest {

    @testSetup static void setup(){
    	//Test Account Creation
		Account testAccount = new Account();
        testAccount.Name = 'Test Account';
        insert testAccount;
		//Test Program Creation
        FieloPLT__Program__c testProgram = new FieloPLT__Program__c();
        testProgram.Name = 'Test Program';
        insert testProgram;

        //Program Point Type and Point Type Id
        FieloPLT__ProgramPointType__c ppt = [SELECT Id, FieloPLT__PointType__c, FieloPLT__RequestPointApproval__c FROM FieloPLT__ProgramPointType__c WHERE FieloPLT__Program__c =: testProgram.Id limit 1];
        testProgram.GRSPointType__c = ppt.FieloPLT__PointType__c;
        testProgram.GRSAccount__c = testAccount.Id;
        update testProgram;

        //Test Member Creation
        FieloPLT__Member__c testMember = new FieloPLT__Member__c();
        testMember.Name = 'Test Member';
        testMember.FieloPLT__Email__c = testMember.Name.deleteWhitespace() + '@fielo.com';
        testMember.FieloPLT__Program__c = testProgram.id;
        insert testMember;

        FieloPLT__Transaction__c trans = new FieloPLT__Transaction__c(FieloPLT__Member__c = testMember.Id, FieloPLT__Points__c = 500);
        trans.FieloPLT__SkipEngine__c = true;
        trans.FieloPLT__IsProcessed__c = true;

        FieloPLT.SObjectService.enableAdminPermission(true);
        insert trans;

        //create a provider order
        FieloPLT__ProviderOrder__c providerOrder = new FieloPLT__ProviderOrder__c(FieloPLT__Account__c = testAccount.Id, GRSOrderNumber__c = '84569');

        //order Items
        List<FieloPLT__RedemptionItem__c> redItems = new List<FieloPLT__RedemptionItem__c>();
        FieloPLT__RedemptionItem__c redItem = new FieloPLT__RedemptionItem__c(FieloPLT__Quantity__c = 1, FieloPLT__Points__c = 20, GRSOrderId__c = '84569-1');
        redItems.add(redItem);

        //call plt api
        FieloPLT__ProviderOrder__c returnedProviderOrder = FieloPLT.RedemptionService.createProviderOrder(testMember.Id, providerOrder, redItems);
    }

    @isTest static void cancelOrderOK(){
        Test.startTest();
        
        RestRequest testRequest = new RestRequest(); 
        RestResponse testResponse = new RestResponse();

        //HTTP Request Type
        testRequest.httpMethod = 'POST';
        //JSON Request Body
        String reqBodyJSON = '{"id": "ABCD1234","orderToken": "ABCDE","type": "cancel","orderId": "84569-1","orderedAt": "2016-08-01 15:09:06","pointCost": 20,"quantity": "1"}';
        RestContext.request = testRequest;
        RestContext.response = testResponse;
 
        //Request URL
        testRequest.requestURI = '/services/apexrest/V1/orders/update/';
        testRequest.requestBody = Blob.valueof(reqBodyJSON);
        
        RESTOrderUpdate.updateOrder();
        
		Test.stopTest();
    }

    @isTest static void cancelOrderWrongId(){
        Test.startTest();
        
        RestRequest testRequest = new RestRequest(); 
        RestResponse testResponse = new RestResponse();

        //HTTP Request Type
        testRequest.httpMethod = 'POST';
        //JSON Request Body
        String reqBodyJSON = '{"id": "ABCD1234","orderToken": "ABCDE","type": "cancel","orderId": "26543-3","orderedAt": "2016-08-01 15:09:06","pointCost": 20,"quantity": "1"}';
        RestContext.request = testRequest;
        RestContext.response = testResponse;
 
        //Request URL
        testRequest.requestURI = '/services/apexrest/V1/orders/update/';
        testRequest.requestBody = Blob.valueof(reqBodyJSON);
        
        RESTOrderUpdate.updateOrder();
        
		Test.stopTest();
    }

    @isTest static void cancelOrderDelivered(){
        FieloPLT__RedemptionItem__c redItem = [SELECT Id FROM FieloPLT__RedemptionItem__c WHERE GRSOrderId__c = '84569-1'];
        redItem.FieloPLT__Status__c = 'Delivered';
        FieloPLT.SObjectService.enableAdminPermission(true);
        update redItem;

        Test.startTest();

        RestRequest testRequest = new RestRequest(); 
        RestResponse testResponse = new RestResponse();

        //HTTP Request Type
        testRequest.httpMethod = 'POST';
        //JSON Request Body
        String reqBodyJSON = '{"id": "ABCD1234","orderToken": "ABCDE","type": "cancel","orderId": "84569-1","orderedAt": "2016-08-01 15:09:06","pointCost": 20,"quantity": "1"}';
        RestContext.request = testRequest;
        RestContext.response = testResponse;
 
        //Request URL
        testRequest.requestURI = '/services/apexrest/V1/orders/update/';
        testRequest.requestBody = Blob.valueof(reqBodyJSON);
        
        RESTOrderUpdate.updateOrder();
        
		Test.stopTest();
    }
}